name: Check SWC Update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.8
          run_install: true
      - name: Run checker script
        run: pnpm ts-node-esm scripts/check-swc-update.ts
      - name: Commit update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: upgrade SWC
          file_pattern: .env
